### PR TITLE
[Sage 9] Update sage-installer to latest dependencies + webpack 5

### PR DESCRIPTION
**Pull request by strarsis**
This PR updates the dependencies of sage-installer, including the dependencies, configuration and other files for the different frameworks and fixes lots of issues (Bulma, Tailwind).

It also adds Bootstrap 5 (Beta2) to the framework selection and fixes Tailwind 2 support.

As Sage 9 uses the `sage-installer` to add framework-specific adjustments, this PR complements the existing Sage 9 PR https://github.com/roots/sage/pull/2607.

### CODE REVIEW

**Comment by strarsis** [comment]
You can test it using `composer create-project`:
https://discourse.roots.io/t/sage-9-2-please-test/20067

**Comment by strarsis** [comment]
@retlehs: Would it be possible to merge this into Sage 9 branch?

**Review by jeffbyrnes — APPROVED** [review]

**Comment by sparkbold** [comment]
Is this PR good so we can use it? I need to upgrade dependencies and Webpack 5 for our new project with Sage 9. Thanks!

**Comment by strarsis** [comment]
@sparkbold: Please check out this guide for using the update branch:
https://discourse.roots.io/t/sage-9-1-please-test/20067?u=strarsis

**Comment by strarsis** [comment]
> @sparkbold: Please check out this guide for using the Sage 9.x update branch:
> https://discourse.roots.io/t/sage-9-1-please-test/20067?u=strarsis

**Comment by jeffbyrnes** [comment]
@sparkbold I’ve used the instructions in that Discourse topic to use this to install this yet-to-be-released version, and it works great.

**Pull request merged**
