### PR TITLE
Add Tailwind CSS preset

### LINKED ISSUE #12: Tailwind CSS Preset
I started working on a PR for this functionality, but ran into a couple issues I'd like to ask about before going further, since I'm not sure it fits in to the build process as easily as other presets. Here are a few issues I ran into:
- Ideally, Tailwind should be included in two different lines, so you can add / extract components before/after the main bulk of the framework to avoid CSS specificity issues. This means `main.scss` has to be modified, which seems like a bit of an anti pattern, since a copy of sorts would have to be maintained in this installer repo.
- Tailwind is configured via a javascript file, which is generated with a node command. I'm not sure any of the other presets do this?
- Tailwind uses PostCSS, and it doesn't seem like any of the other presets do this either. This requires adding a line to `webpack.config.js` like `tailwindcss: './tailwind.js'`. Additionally, this causes some stylelinter errors too, and the tailwind-specific at-rules (i.e. `@tailwind`) need to be added to the excludes array for stylelinter in `package.json`.

Given the above problems, would Tailwind CSS still be considered as a preset? I'm happy to keep working on it if so, but otherwise a short guide or docs piece might be more appropriate when sage v9 is fully released. Thanks!

### PR DESCRIPTION
**Pull request by knowler**
This is a work in progress. So far I’ve just added the stubs for a [Tailwind CSS](https://tailwindcss.com/) preset as I figured it would be good to know what we are trying to generate. A lot of this is based on [my guide for adding Tailwind to Sage](https://roots.io/guides/how-to-setup-tailwind-css-in-sage/), however, there are some differences:

1. `tailwind.js` will be called `tailwind.config.js` to follow Sage’s config file naming scheme. It still does live in `styles` though, which could be discussed (read more: 589b623).
2. I’ve added a few changes to Tailwind’s config: (see 31c2503)
    1. Add Sage primary colour.
    2. Add Sage primary colour (30%) to `.shadow-outline`.
    3. Centre + add padding to the container.
3. I’ve added some styles via Tailwind’s `@apply` to replace the Bootstrap ones. This is a work in progress as there are a few partials left to do. I would like feedback about whether or not we should be adding these. I had noticed the todo comments in the Tachyons stubs so I figured I would give it a shot for Tailwind.

The installer will need to do the following:

- [x] Add Tailwind to the `devDependencies`.
- [x] Add Tailwind at-rules to `package.json`.
- [x] Add the modified PostCSS config.
- [x] Add the Tailwind config.
- [x] Add updated `main.scss` and partials.
- [x] On subsequent preset change, remove Tailwind-specific files
- [x] On subsequent preset change, remove Tailwind-specific at-rules

Left to do for the stubs:

- [x] Add search form styles.
- [x] Add styles for classes generated for WordPress.

Resolves #12.

### CODE REVIEW

**Comment by mmirus** [comment]
Nice work, @knowler. Can take a look at your stubs if you'd like, but I trust your judgment on that front.

On my end, I pushed changes that that add the Tailwind preset option and set the installer up to copy the stubs to the theme. This PR is now functional.

As we discussed, I used a `PATH` repository to test locally, and updated the `sage-installer` version to point to the branch. Sage `composer.json`:

```json
  "repositories": [
    {
      "type": "path",
      "url": "../sage-installer",
      "options": {
        "symlink": false
      }
    }
  ],
  ..
  "require-dev": {
    "squizlabs/php_codesniffer": "^2.8.0",
    "roots/sage-installer": "dev-tailwind-preset"
  },
```

Turning off symlinks was required to work around this error:

```sh
$ ./vendor/bin/sage preset
PHP Fatal error:  Uncaught Error: Class 'Roots\Sage\Installer\Installer' not found in C:\git\sage-installer\bin\sage:8
Stack trace:
#0 {main}
  thrown in C:\git\sage-installer\bin\sage on line 8

Fatal error: Uncaught Error: Class 'Roots\Sage\Installer\Installer' not found in C:\git\sage-installer\bin\sage:8
Stack trace:
#0 {main}
  thrown in C:\git\sage-installer\bin\sage on line 8
```

**Comment by knowler** [comment]
This is fully functional with roots/sage#2084. There are still missing stubs that I’ve left blank with a note TODO for now. I really don’t imagine a Tailwind user would rely on these styles by default — it just makes the default built styles not so plain (`@tailwind preflight` is an aggressive reset, i.e. removes margin from `p` and `h1-6`).

**Comment by knowler** [comment]
If everything looks good, we are ready to rock. 🤘

An warning will still appear when running `yarn start` until we figure something out for roots/sage#2084.

**Comment by mmirus** [comment]
Once https://github.com/roots/sage/pull/2084 is merged, this will work correctly. Otherwise, the merge method in https://github.com/roots/sage/pull/2083 breaks the Webpack config when this preset is used.

If the user changes from the Tailwind preset to another preset that doesn't overwrite all of the SCSS files that the Tailwind preset modifies, Tailwind `@apply` directives are left behind. This isn't pretty, but it's consistent with the installer's general behavior when switching presets.

Otherwise, I reviewed everything and didn't spot any problems besides the path fixed in https://github.com/roots/sage-installer/pull/22/commits/615dc71ef219e13bd769dcd0e795fb863fb830b0.

Thanks again for all your work on this @knowler!

**Comment by knowler** [comment]
So using `webpack.config.preset.js` to remove a loader doesn't isn’t possible due to limitations with `webpack-merge`, so instead, since it's just a warning that's being thrown, we enable the `silent` option for `resolve-url-loader` and explicitly disable all the source maps since they throw errors in the browser console since, when using Tailwind, you don't really use them anyway.

This is ready for merge if it looks good. roots/sage#2084 still needs to be merged first though.

Read more:
https://github.com/tailwindcss/tailwindcss/issues/48#issuecomment-341423237

**Pull request merged**
